name = "ReplicationPackage_KexinCHEN_JinxuMI"
uuid = "0380cd6f-96bf-46b7-8328-1780768c80b0"
authors = ["KexinChen1999 <chenkexin.vincent@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
